# Generated by Django 4.2.2 on 2023-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_name', models.CharField(max_length=50)),
                ('crm_lastname', models.CharField(max_length=50)),
                ('crm_number', models.CharField(max_length=15)),
                ('crm_email', models.EmailField(max_length=254)),
                ('crm_password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
            },
        ),
    ]
