# Generated by Django 4.2.2 on 2023-08-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmsystem',
            name='crm_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='crmsystem',
            name='crm_lastname',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='crmsystem',
            name='crm_name',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='crmsystem',
            name='crm_number',
            field=models.CharField(max_length=15, verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='crmsystem',
            name='crm_password',
            field=models.CharField(max_length=128, verbose_name='Hasło'),
        ),
    ]
