# Generated by Django 4.2.2 on 2023-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='zdjecia/')),
                ('header', models.CharField(max_length=40, verbose_name='Nagłówek')),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(verbose_name='Treść')),
            ],
        ),
    ]
