# Generated by Django 4.2.2 on 2023-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Wiadomość', 'verbose_name_plural': 'Wiadomości'},
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nagłówek'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia/'),
        ),
    ]
